bot:
  token: 8080230088:AAF2m5fdI92cHIAxz-kzoQCn9kGotyDMiK8
  name: tolmic_bot

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 1
      chat:
        options:
          model: llama3.1
          temperature: 0.7
      embedding:
        options:
          model: hf.co/mixedbread-ai/mxbai-embed-large-v1
  # mxbai-embed-large
  # hf.co/mixedbread-ai/mxbai-embed-large-v1
  datasource:
    url: jdbc:postgresql://localhost:5432/vacancy
    username: postgres
    password: dima
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    security:
      oauth2:
        client:
          registration:
            my-client:
              client-id: MKO05LHS6HCOUOEHIP2H5UEH4C8PP4CT0JEG78CELRGV7B7316C0CP7V5O6LJP2D
              client-secret: SCVD4U5PJJPOMR90AOHO6VKN9FR912MLO2V6SQRVCDS01C2AAQJR4VK78GIEASRA

